[package]
name = "safetynet"
description = "A Rust-embedded bytecode VM for CTF reversing challenges."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
safetynet-core.workspace = true
safetynet-macros.workspace = true

[dev-dependencies]
macrotest = "1"
proptest = "1"
trybuild = "1"

[lints]
workspace = true
