[package]
name = "safetynet"
description = "A Rust-embedded bytecode VM for CTF reversing challenges."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
safetynet-core.workspace = true

[lints]
workspace = true
